import type { QuestionnaireValues } from "@/lib/validations/profile";

export const questionnaireDefaults: QuestionnaireValues = {
  name: "",
  email: "",
  gender: "male",
  isInitiated: "no",
  initiatedName: "",
  birthDate: "",
  birthTime: "",
  birthPlace: "",
  caste: "",
  height: "",
  weight: "",
  languages: "",
  education: "",
  working: "yes",
  profession: "",
  jobLocation: "",
  salary: "",
  widow: "no",
  divorced: "no",
  relocate: "yes",
  phone: "",
  familyPhone: "",
  city: "",
  state: "",
  address: "",
  counsellor: "",
  counsellorPhone: "",
  rounds: "",
  regs: [],
  familyMembers: "",
  homeAddress: "",
  homeCategory: "owned",
  father: "",
  mother: "",
  sibling: "",
  parentsChanting: "both",
  aboutYou: "",
  expectations: "",
  photoUrl: "",
  photoKey: "",
};
